on:
  workflow_dispatch:
jobs:
  win-build:
    name: build-for-windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
